package com.company.gsap.generator;

import com.company.gsap.loader.dto.ShapeMetadataDTO;

/**
 * Owns the string templates for generated ShapeTransformer files.
 *
 * Supports two modes:
 *   - Legacy (v1.0): hardcoded package/imports for backward compat
 *   - Parametric (v2.0): uses correct target API (com.core.*)
 *
 * If you need to change how the output file looks, change this class.
 * If you need to change how edges are processed, change the generators.
 */
public class ShapeTemplate {

    // ── Legacy template (v1.0) — kept for backward compatibility ──────────

    private static final String LEGACY_HEADER = """
            package com.company.gsap.generated;

            import java.awt.geom.Point2D;
            import java.util.List;
            import java.util.Map;
            import java.util.ArrayList;

            /**
             * Auto-generated ShapeTransformer for: %s
             * Generated by GSAP Geometry Core
             *
             * DO NOT EDIT — regenerate from the source JSON instead.
             */
            public class %s extends ShapeTransformer {

                @Override
                public List<Edge> resize(Param param, ParamList paramList) {
            """;

    private static final String LEGACY_FOOTER = """

                    double circumference = calculateCircumference(edges);
                    return edges;
                }
            }
            """;

    // ── Parametric template (v2.0) — correct target API ──────────────────

    private static final String PARAMETRIC_HEADER = """
            package %s;

            import com.core.edge.Edge;
            import com.core.edge.StraightEdge;
            import com.core.edge.builder.EdgeBuilder;
            import com.core.math.Point2D;
            import com.core.shape.Param;
            import com.core.shape.ParamList;
            import com.core.shape.ShapeConstants;
            import com.core.shape.transformer.ShapeTransformer;
            import com.core.utility.EdgeDimCutTuple;
            import java.util.ArrayList;
            import java.util.List;
            import java.util.Map;

            /**
             * Auto-generated ShapeTransformer for: %s
             * Generated by GSAP Geometry Core
             * DO NOT EDIT — regenerate from the source JSON instead.
             */
            public class %s extends ShapeTransformer {
            """;

    private static final String PARAMETRIC_FOOTER = """
            }
            """;

    // ── Public API ──────────────────────────────────────────────

    /**
     * Assembles a complete Java file in legacy (v1.0) format.
     */
    public String buildFile(String shapeName, String className, String body) {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format(LEGACY_HEADER, shapeName, className));
        sb.append(body);
        sb.append(LEGACY_FOOTER);
        return sb.toString();
    }

    /**
     * Assembles a complete Java file in parametric (v2.0) format.
     *
     * @param metadata   shape metadata (className, packageName, etc.)
     * @param shapeName  the original shape name (for the doc comment)
     * @param resizeBody     the generated resize() method body
     * @param resize2Body    the generated resize2() method body (may be null)
     * @param calcAreaBody   the generated calculateArea() method body (may be null)
     * @return the full Java source file as a string
     */
    public String buildParametricFile(ShapeMetadataDTO metadata, String shapeName,
                                       String resizeBody, String resize2Body,
                                       String calcAreaBody) {
        String packageName = metadata != null && metadata.packageName != null
                ? metadata.packageName
                : "com.core.shape.transformer.impl";
        String className = metadata != null && metadata.className != null
                ? metadata.className
                : "ShapeTransformer_" + shapeName.replaceAll("[^a-zA-Z0-9_]", "_");

        StringBuilder sb = new StringBuilder();
        sb.append(String.format(PARAMETRIC_HEADER, packageName, shapeName, className));

        // resize() method
        sb.append("\n    @Override\n");
        sb.append("    public List<Edge> resize(List<Param> params, Map<String, Double> services) {\n");
        sb.append(resizeBody);
        sb.append("    }\n");

        // resize2() method
        if (resize2Body != null) {
            sb.append("\n    @Override\n");
            sb.append("    public EdgeDimCutTuple resize2(\n");
            sb.append("            List<Param> params,\n");
            sb.append("            Map<String, Double> services,\n");
            sb.append("            Map<String, Double> coatingRemovals) {\n");
            sb.append(resize2Body);
            sb.append("    }\n");
        }

        // calculateArea() method
        if (calcAreaBody != null) {
            sb.append("\n    private void calculateArea(List<Param> params) {\n");
            sb.append(calcAreaBody);
            sb.append("    }\n");
        }

        sb.append(PARAMETRIC_FOOTER);
        return sb.toString();
    }
}
