package com.company.gsap.generator;

/**
 * Owns the string templates for generated ShapeTransformer files.
 *
 * Purely about formatting — no logic, no loops, no edge processing.
 * If you need to change how the output file looks, change this class.
 * If you need to change how edges are processed, change CodeGenerator.
 */
public class ShapeTemplate {

    // ── Template constants ──────────────────────────────────────

    private static final String HEADER = """
            package com.company.gsap.generated;

            import java.awt.geom.Point2D;
            import java.util.List;
            import java.util.Map;
            import java.util.ArrayList;

            /**
             * Auto-generated ShapeTransformer for: %s
             * Generated by GSAP Geometry Core
             *
             * DO NOT EDIT — regenerate from the source JSON instead.
             */
            public class %s extends ShapeTransformer {

                @Override
                public List<Edge> resize(Param param, ParamList paramList) {
            """;

    private static final String FOOTER = """

                    double circumference = calculateCircumference(edges);
                    return edges;
                }
            }
            """;

    // ── Public API ──────────────────────────────────────────────

    /**
     * Assembles a complete Java file from the generated method body.
     *
     * @param shapeName the original shape name (used in the doc comment)
     * @param className the class name (e.g. ShapeTransformer_TestRectangle)
     * @param body      the generated point declarations + EdgeBuilder chain
     * @return the full Java source file as a string
     */
    public String buildFile(String shapeName, String className, String body) {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format(HEADER, shapeName, className));
        sb.append(body);
        sb.append(FOOTER);
        return sb.toString();
    }
}
