package com.company.gsap.generator;

/**
 * Template for ShapePreview classes.
 * ShapePreview provides visualization and metadata for shapes before manufacturing.
 */
public class ShapePreviewTemplate {

    private static final String HEADER = """
            package com.company.gsap.generated.preview;

            import java.awt.geom.Point2D;
            import java.util.List;
            import java.util.Map;
            import java.util.HashMap;
            import java.util.ArrayList;

            /**
             * Auto-generated ShapePreview for: %s
             * Generated by GSAP Geometry Core v2.0
             *
             * Provides shape metadata, parameters, and preview coordinates.
             * DO NOT EDIT — regenerate from the source JSON instead.
             */
            public class %s {

                private final Map<String, Parameter> parameters = new HashMap<>();
                private final Map<String, String> metadata = new HashMap<>();

                public %s() {
                    initializeParameters();
                    initializeMetadata();
                }

            """;

    private static final String FOOTER = """

                /**
                 * Gets all shape parameters.
                 */
                public Map<String, Parameter> getParameters() {
                    return new HashMap<>(parameters);
                }

                /**
                 * Gets shape metadata.
                 */
                public Map<String, String> getMetadata() {
                    return new HashMap<>(metadata);
                }

                /**
                 * Calculates preview points with default parameter values.
                 */
                public Map<String, Point2D> getPreviewPoints() {
                    Map<String, Double> paramValues = new HashMap<>();
                    parameters.forEach((name, param) -> paramValues.put(name, param.defaultValue));
                    return calculatePoints(paramValues, 0.0, 0.0); // Use 0,0 as origin for preview
                }

                /**
                 * Calculates points with custom parameter values and trim offsets.
                 */
                public Map<String, Point2D> calculatePoints(Map<String, Double> paramValues, 
                                                             double trimLeft, double trimBottom) {
                    Map<String, Point2D> points = new HashMap<>();
            %s
                    return points;
                }

                /**
                 * Parameter definition class.
                 */
                public static class Parameter {
                    public final String name;
                    public final String type;
                    public final double defaultValue;
                    public final String description;

                    public Parameter(String name, String type, double defaultValue, String description) {
                        this.name = name;
                        this.type = type;
                        this.defaultValue = defaultValue;
                        this.description = description;
                    }
                }
            }
            """;

    /**
     * Builds a complete ShapePreview Java file.
     */
    public String buildFile(String shapeName, String className, 
                           String paramInitBody, String metadataBody, String pointCalcBody) {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format(HEADER, shapeName, className, className));
        sb.append(paramInitBody);
        sb.append(metadataBody);
        sb.append(String.format(FOOTER, pointCalcBody));
        return sb.toString();
    }
}
